language: cpp

compiler:
 - gcc

before_install:
 - git submodule update --init --recursive
 - sudo pip install cpp-coveralls
 - sudo add-apt-repository ppa:ubuntu-toolchain-r/test -y
 - sudo apt-get update
 - sudo apt-get install valgrind python-yaml libyaml-dev build-essential libssh2-1-dev libarchive-dev clang
 - sudo apt-get install gcc-4.9 g++-4.9
 - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.9 20
 - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.9 20
 - sudo update-alternatives --install /usr/bin/gcov gcov /usr/bin/gcov-4.9 20
 - sudo update-alternatives --config gcc
 - sudo update-alternatives --config g++

script:
 - ./configure && make

branches:
    only:
        - master	
